dags:
  outputs:
    dev:
      dataset: sandbox
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      method: oauth
      priority: interactive
      project: data-playground-sandbox
      threads: 1
      type: bigquery
  target: dev
